"""initial schema

Revision ID: 446283d832f2
Revises: 
Create Date: 2026-03-03 23:59:08.156160+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '446283d832f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True, comment='2-char USPS state code'),
    sa.Column('website', sa.Text(), nullable=True, comment='Canonical root domain, e.g. acmetax.com'),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('revenue_est_min', sa.Integer(), nullable=True, comment='Lower bound of revenue estimate in thousands USD'),
    sa.Column('revenue_est_max', sa.Integer(), nullable=True, comment='Upper bound of revenue estimate in thousands USD'),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True, comment='One of: private, pe_backed, public, franchise, unknown'),
    sa.Column('union_affiliated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True, comment="'erc_primary' | 'property_tax_only' | 'union' | 'out_of_geo'"),
    sa.Column('thesis_fit_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('primary_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ownership_type IN ('private', 'pe_backed', 'public', 'franchise', 'unknown')", name='ck_company_ownership_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state', name='uq_company_name_state')
    )
    op.create_index('idx_companies_active', 'companies', ['is_excluded'], unique=False, postgresql_where=sa.text('is_excluded = FALSE'))
    op.create_index('idx_companies_services_gin', 'companies', ['services'], unique=False, postgresql_using='gin')
    op.create_index('idx_companies_state', 'companies', ['state'], unique=False)
    op.create_table('thesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revenue_min', sa.Integer(), nullable=True, comment='Minimum revenue in thousands USD'),
    sa.Column('employee_min', sa.Integer(), nullable=True),
    sa.Column('states', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of 2-char state codes; NULL = all continental US'),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ownership', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('companies_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicates_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_pipeline_run_status'),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_thesis_id'), 'pipeline_runs', ['thesis_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False, comment="Collector identifier: 'google_places' | 'state_filings' | 'ascsp' | 'web_scraper' | 'manual_import'"),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_records_payload_gin', 'raw_records', ['raw_payload'], unique=False, postgresql_using='gin')
    op.create_index('idx_raw_records_unprocessed', 'raw_records', ['processed'], unique=False, postgresql_where=sa.text('processed = FALSE'))
    op.create_index(op.f('ix_raw_records_company_id'), 'raw_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_raw_records_source_name'), 'raw_records', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_records_source_name'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_company_id'), table_name='raw_records')
    op.drop_index('idx_raw_records_unprocessed', table_name='raw_records', postgresql_where=sa.text('processed = FALSE'))
    op.drop_index('idx_raw_records_payload_gin', table_name='raw_records', postgresql_using='gin')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_pipeline_runs_thesis_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('thesis')
    op.drop_index('idx_companies_state', table_name='companies')
    op.drop_index('idx_companies_services_gin', table_name='companies', postgresql_using='gin')
    op.drop_index('idx_companies_active', table_name='companies', postgresql_where=sa.text('is_excluded = FALSE'))
    op.drop_table('companies')
    # ### end Alembic commands ###
